### PR TITLE
Mongo::InvalidNSName - database names cannot contain the character '.':


### PR DESCRIPTION
**Pull request by fairchild**
I was getting the error in the title, so changed the database names to use - instead of .

Here is the relevant section from the mongo driver:

```
# File 'lib/mongo/util/support.rb', line 48

def validate_db_name(db_name)
  unless [String, Symbol].include?(db_name.class)
    raise TypeError, "db_name must be a string or symbol"
  end

  [" ", ".", "$", "/", "\\"].each do |invalid_char|
    if db_name.include? invalid_char
      raise Mongo::InvalidNSName, "database names cannot contain the character '#{invalid_char}'"
    end
  end
  raise Mongo::InvalidNSName, "database name cannot be the empty string" if db_name.empty?
  db_name
end
```

### CODE REVIEW

**Comment by assaf** [comment]
From the [MongoDB specification](http://www.mongodb.org/display/DOCS/Collections):

> Collections can be organized in namespaces; these are named groups of collections defined using a dot notation. For example, you could define collections blog.posts and blog.authors, both reside under "blog".

**Comment by assaf** [comment]
To elaborate:

Database names cannot contain dots

Collection names can contain dots

This pull request was to remove dots from collections, although the exception has nothing to do with collections, and collections do allow dots.

If you see this error in your code, chances are you set Server.database to a MongoDB _connection_ instead of a database object.

**Comment by fairchild** [comment]
Yep, yer right.  thanks

**Comment by zambon** [comment]
How about this, any clues? I made sure I'm using a connection object, not a database one.

```
> Rack::OAuth2::Server.get_issuer 'www.facebook.com'
Mongo::InvalidNSName: collection names must not start or end with '.'
```

If it helps:

mongoid (2.4.12)
rack-oauth2-server (2.8.0)

**Comment by zambon** [comment]
Forcing `oauth.collection_prefix = 'oauth2'` did the trick.

**Pull request closed without merging**
